# Generated by Django 3.2 on 2022-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(default=65.79, max_length=254),
        ),
    ]
