# Generated by Django 3.2 on 2022-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
