# Generated by Django 3.2 on 2022-07-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
