# Generated by Django 3.2 on 2022-07-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterusers',
            options={'verbose_name_plural': 'NewsletterUsers'},
        ),
    ]
